[DR-3282] Add Pact provider support for integration with WDS consumer (#1528)
* first pass at some verification

* test update and gradle task

* some updates

* use more anys

* Create verify_consumer_pacts.yaml

First attempt at copying yaml over

* Update verify_consumer_pacts.yaml

Try a better copy of verify pacts yaml

* rename tdr-provider

* Show standard stream logging output for Pact verification tests

* Categorize Pact tests with @Tag

Create reusable Pact.TAG to tag Pact tests, following existing repository convention.

* Spotless

* Debug why Pact verification isn't running

* Set up Pact test with Spring boot test slicing

This follows existing convention in SnapshotsApiControllerTest:
by only loading in the required SnapshotsApiController into the context and mocking all of its inputs,
I want to see what's actually required when setting up the application context before introducing additional env variables.
While here, also broke out the reused UUID into a variable.

* Try to enable Gradle build scans for Pact tests

And enabled standard logging for easier debugging (default is JSON).

* Pact broker URL shouldn't specify https prefix

Pact tests were failing with:
au.com.dius.pact.provider.junitsupport.loader.NoPactsFoundException: No Pact files were found to verify
Provider: tdr
Source: Pact Broker http://https://pact-broker.dsp-eng-tools.broadinstitute.org

* Use HTTPS when resolving Pact Broker

* Instruct Pact context to use MockMvc as its target

* GlobalExceptionHandler must be loaded in Pact verification test slicing

Otherwise, when we've configured our mocks to throw, our controller will not be able to properly handle the exceptions.
We've run into this for other MVC unit tests before: see SnapshotsApiControllerTest.java.

* Pass Pact username and password to Gradle verifyTests target

* Rename provider to match Helm chart name: datarepo

This will allow for our deployments to be recorded.
This also lays the groundwork to use the same name for both TDR as a consumer and provider, which allows for clearer construction of Pact Broker's network graph.

* Update documentation to include Pact broker credential management

We needed to make a Terraform change so that the Pact broker credentials could be managed by Atlantis and exposed as GHA env variables.

* Update au.com.dius.pact.provider:junit5spring to latest

* Update au.com.dius.pact.provider:junit5 to latest

* Downgrade au.com.dius.pact.provider to previously working version

Was seeing 'Cannot invoke getPreferredVersion because versionConstraint is null'

* Simplify Provider states to the minimum required

This reduces ongoing maintenance burden and better reflects the expectations that WDS has of TDR.
Upgraded to latest compatible pact plugins.
Moved away from deprecated host and scheme system properties in favor of setting pactbroker.url.
Since this is getting set in a test profile, we should no longer need to pass it as an environmentn variable in GHA verify_consumer_pacts.

* Snapshot provider states expect ID to be specified in params

This allowed us to remove a hardcoded dummy snapshot UUID which needed to match the one that WDS was using.
WDS contract tests will need to change to supply this ID.

* Update Provider state names to reflect expected parameters

These names now match the states referenced by our sole consumer, WDS

* Remove what I think is a redundant Pact plugin?

* Add instructions for verifying Pacts locally

We need to populate environment variables with the Pact broker's RO username and password.
This is achieved through an expansion of render-configs.sh, but developers will need to update
however they define their environment variables for this to work.

* Break out Pact test config into separate script

Only a very small amount of pre-configuration is required to verify Pact contracts: I want a dev to be able to verify contracts without getting bogged down in extraneous set-up.

* Add consumerVersionSelectors to Pact provider set-up

This makes it so that Pact provider verification will pick up on the expected consumer Pacts from the broker.
Included documentation on how to expand the selector if you wish to pick up Pacts from a consumer's feature branch.
In coordination with WDS consumer, expanded 'user has access to snapshot with given id' provider state to include a table:
this consumer expects that a snapshot retrieved with tables will have at least one table with a name.

* Rollback SnapshotService method signature changes committed by mistake

* Add missing SnapshotDaoTest for retrieving nonexistent snapshot

* Rename DataRepoProviderTest -> SnapshotsApiControllerTest

We want to set boundaries for how we define our Provider states: if future Consumers end up calling other non-snapshot endpoints, we should set up new corresponding Provider state classes.
Note that this name matches existing MockMvc unit test SnapshotsApiControllerTest: I'll seek PR feedback on whether the matching name helps or hurts us.

* Add unit test to verify SnapshotNotFoundException's class lineage

* Establish Pact provider state method naming convention

* Enable test logging for Pact provider verification

---------

Co-authored-by: Bria Morgan <bmorgan@broadinstitute.org>
Co-authored-by: Bria Morgan <calypsomatic@gmail.com>