[DCJ-503] Gracefully handle DRS resolution failure case for self-hosted snapshots
In production, we are seeing some DRS resolution attempts fail with an NPE:

java.lang.NullPointerException: Cannot invoke \"com.google.cloud.storage.Bucket.getLocation()\" because \"bucket\" is null"

Reading the corresponding stack trace shows that this is happening for self-hosted GCP snapshots.

Gracefully handle the case where TDR cannot obtain the GCS bucket for a file object within a self-hosted GCP snapshot, and provide diagnostic information on the source snapshot, root dataset, and file object in the error details.