[DCJ-400-gradle] Upgrade io.swagger.codegen.v3 deps 3.0.61 -> 3.0.62 (#1801)
* [DCJ-400-gradle] Upgrade io.swagger.codegen.v3 deps 3.0.61 -> 3.0.62

This patch upgrade without changing configuration caused compilation of Swagger generated code to fail with the following errors:

```
/github/workspace/build/generated-src/swagger/src/main/java/bio/terra/model/ResourcePolicyModel.java:10: error: package io.swagger.configuration does not exist
import io.swagger.configuration.NotUndefined;
                               ^
/github/workspace/build/generated-src/swagger/src/main/java/bio/terra/model/ResourcePolicyModel.java:21: error: cannot find symbol
@NotUndefined
 ^
```

For now, setting `validationMode=legacy` but think this might be another bug in swagger-codegen-generators.

* Don't include io.swagger.codegen.v3 deps in our grouped Dependabot PRs

Patch upgrades have lately included breaking changes.
But, we do want to keep swagger-codegen and swagger-codegen-cli versions in sync with each other, so introduce a new dependency grouping for them.